### ISSUE TITLE
Not compatible with current Notepad ++

### ISSUE THREAD

**Issue by NDevox** [wakatime/notepadpp-wakatime#13]
I get the following error when opening Notepad++ with the plugin installed:

```
Failed to load

This plugin is not compatible with the current version of Notepad++.
```

I'm on version 6.8.3. It might be possible that it's a proxy issue being behind my work firewall. But I am transmitting data from PyCharm so I'm inclined to think that isn't the case.

**Comment by NDevox** [comment]
No log found.

Is this unicode or ANSI?

If it isn't unicode that'll probably be the problem: http://docs.notepad-plus-plus.org/index.php?title=Plugin_Development#Converting_plugins. 

I'd love to apply a patch but don't know much (any) C#.

**Comment by alanhamlett** [comment]
Not related to unicode/ansi because Notepad++ is only releasing the unicode version now. I just tested with unicode v6.8.5 build 393301 and didn't get the error message.

Maybe it's a bug with NPP v6.8.3, can you upgrade Notepad++? If it's still happening with the latest version, maybe it's a 64bit problem, since I tested only on 32bit Windows.

**Comment by NDevox** [comment]
Was hoping it would be an easy fix, guess not then.

Upgraded to 6.8.5 but same error. 

Might be a 64bit problem - what version of Windows do you have?

**Comment by alanhamlett** [comment]
Windows 8.1 32bit from https://dev.modern.ie/tools/vms/

Downloading Windows 10 VM now to see if it has the error.

**Comment by NDevox** [comment]
tried win7 32-bit form above site (sorry this took me ages to get back to) - which reflects my work build.

Same error raised.

**Comment by alanhamlett** [comment]
Are you installing via Plugin Manager inside Notepad++? I haven't been able to reproduce this when using the latest version available through Plugin Manager.

**Comment by NDevox** [comment]
I believe I'm connected through the vm (and through work) by proxy and have been unable to find which port to go through. So these are downloaded DLLs from the release page which are then pasted into the plugins folder.

**Comment by NDevox** [comment]
Note: proxy connections mean I can't access plugins through the plugin manager.

**Comment by alanhamlett** [comment]
Oh, that would prevent the plugin from downloading it's dependencies ([wakatime-cli](https://github.com/wakatime/wakatime) and embeddable-python). Can you add your proxy to your `$HOME/.wakatime.cfg` file and restart Notepad++?

Here's an example of the expected proxy format:
https://github.com/wakatime/wakatime#configuring

**Comment by alanhamlett** [comment]
The .cfg file should be located in your User home directory:
`C:\Users\<user>\AppData\Roaming\Notepad++\plugins\config\.wakatime.cfg`

After adding your https proxy to the config file and making sure WakaTime plugin is installed in Notepad++:
1. restart Notepad++
2. open any existing file, type something and save
3. check `C:\Users\<user>\AppData\Roaming\Notepad++\plugins\config\WakaTime.log` for error messages
4. check `C:\Users\<user>\.wakatime.log` for error messages

**Comment by NDevox** [comment]
Added in latest build of the plugin.

Setup the config file in the directory (edited the already existing config file). Now has proxy address (not convinced it is right but assuming there would be an error in logs if it is wrong). debug = true.

Restarted and edited a file. (error still comes up on restarting).

Checked the two log file locations (only get one in users\user.wakatime.log). No logs recorded since December.

Still failing :-. Any reason why it wouldn't be logging?

**Comment by alanhamlett** [comment]
Fixed with 83d0bb0741ebcc2b94117b1408d47dcca8fddd53 and released in v3.0.2.

**Comment by nelson6e65** [comment]
I'm still having this problem in **`Notepad++ 6.9.2`**, Windows 7 (x86), using dll [`4.0.2`](https://github.com/wakatime/notepadpp-wakatime/releases/tag/4.0.2):

![wakatimepluginincompatible](https://cloud.githubusercontent.com/assets/9272498/17877903/db2c7d02-68b4-11e6-977b-cb00cfae7cbf.png)

**Comment by alanhamlett** [comment]
Can you delete the `WakaTime.dll` file in `C:\Program Files\Notepad++\plugins\` and then re-install the plugin through the Plugin Manager to make sure it's the latest version?

**Comment by nelson6e65** [comment]
> @alanhamlett 
> Can you delete the WakaTime.dll file in C:\Program Files\Notepad++\plugins\ and then re-install the plugin through the Plugin Manager to make sure it's the latest version?

Done! (It installs the same version of WakaTime plugin I downloaded: 0.4.2. 

But still the same notification. Not working. :worried:
(Actually, it craches if I don't uninstall the plugin.

**Comment by alanhamlett** [comment]
I'm not able to reproduce this, testing on a Windows 7 (x86) Virtual Machine set to Spanish language. Installing v4.0.2 works there:
<img width="694" alt="screen shot 2016-08-23 at 6 17 36 pm" src="https://cloud.githubusercontent.com/assets/522344/17900281/f2084eca-695e-11e6-9709-91bcadfdee6c.png">

@bruderstein maybe you can help show us how to find an error message showing the problem?

**Comment by nelson6e65** [comment]
Well... I did reinstall `Notepadd++` 2 times and now `Wakatime` plugin is not crashing. :smiley:

I don't know why this happened :confused:, but well... :smile:

Thanks for answering! :relaxed:

**Comment by alanhamlett** [comment]
Ok, closing this issue since it's working now.

**Comment by acrolink** [comment]
I have encountered a similar problem when developing a dotNet c# based notepad++ plug-in. Compiled in VS 2017 gives the error while compiled using VS 2015 works fine.

**Comment by jasminrueegger** [comment]
The reply from acrolink contained the necessary info: That plugin requires VisualC++ Runtime 2017 x64. After installing vcredist, the error message dissappeared and the plugin is working.

**Comment by alanhamlett** [comment]
Also #33 and v4.1.0 might have fixed this.
