### ISSUE TITLE
Notepad++ freezes and can't be clicked on anywhere.

### ISSUE THREAD

**Issue by Panzerbjrn** [wakatime/notepadpp-wakatime#48]
Similar to issue #34 , my Notepad++ will hang/freeze, several times throughout the day when I have the WakaTime plugin installed.
If I uninstall it, the problem goes away.

If I doubleclick a text file, it opens into NP++, but it remains otherwise frozen.

I have tried re-installing the plugin, but with no success.

This happens across two laptops, work  & personal. Both are Win 10 with the latest updates, NP++ is 8.1.9.2 & 8.1.2 respectively.

Is this something I can prevent somehow?

**Comment by ola-pt** [comment]
I have to force the process to stop and then restart; after that, it will work for a while before freezing again.

**Comment by Cyborgindustries** [comment]
Yeah, same issue.. it's a shame as I really liked the idea of wakatime

Windows 11
Notepad++ v8.3.3
Plugin v4.2.3

if notepad++ idles for too long it becomes unresponsive and only closable via task manager

**Comment by QuentiumYT** [comment]
Same issue for several month now (updating NP++ somtimes)
I'll uninstall wakatime plugin for now as it's getting really annoying, hope there would be a fix soon

**Comment by alanhamlett** [comment]
Fixed with 4bfda5fe30b3f2bc9c99b19742ef41509531b15e.

**Comment by seowner** [comment]
> Fixed with [4bfda5f](https://github.com/wakatime/notepadpp-wakatime/commit/4bfda5fe30b3f2bc9c99b19742ef41509531b15e).

This is not fixed sadly... I just started using Wakatime and it freezes and I can't click anywhere. Happened 3 times today already and I've had to force close... which is unsustainable.

NP++ v8.4.6
WakaTime 4.2.3

**Comment by seowner** [comment]
Also @alanhamlett, this is sadly not fixed... as you can see in #46. It's happening just as frequently... maybe even more so than the previous version.
